# Nome do fluxo
name: CI

# Aciona o fluxo quando:
on:
  # Houver um pull
  pull_request:
    branches: [ "main" ]
  # Permite a execução manual
  workflow_dispatch:

# Fluxo de trabalho
jobs:
  CI:
    runs-on: ubuntu-latest
    
    # Passos do fluxo de trabalho
    steps:
    
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      
      - name: Instalando dependências
        run: npm install

      - name: Executando testes
        run: npm run test -- --coverage
        env:
          CI: true
          
      - name: SonarCloud Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=yurigadelha1 \
          -Dsonar.projectKey=yurigadelha1_java-api \
          -Dsonar.language=java \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dmaven.test.skip=true 
